# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

project_name: sandstorm-tracker

before:
  hooks:
    - go mod tidy
#     # Repository to push the app manifest to.
#     repository:
#       owner: daniel-le97
#       name: scoop-bucket
#       branch: main
#       token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
#
#     # Git author used to commit to the repository.
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#
#     # The project name and current git tag are used in the format string.
#     commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
#
#     # Setting this will prevent goreleaser to actually try to commit the updated
#     # manifest - instead, the manifest file will be stored on the dist folder
#     # only, leaving the responsibility of publishing it to the user.
#     skip_upload: false
# you may remove this if you don't need go generate
# - task sqlc

builds:
  - id: build_noncgo
    main: ./
    binary: sandstorm-tracker
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.Date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    # include additional files in the archive
    files:
      - README.md
      - LICENSE
      # - banned.db     # Include SQLite database with releases
      # - ./scripts/install.sh    # Include installer script

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: daniel-le97
    name: sandstorm-tracker

  # If set to true, will not auto-publish the release.
  # Available only for GitHub and Gitea.
  draft: false

  # Whether to remove existing draft releases with the same name before creating
  # a new one. Only effective if `draft` is set to true.
  # Available only for GitHub.
  replace_existing_draft: true

  # Useful if you want to delay the creation of the tag in the remote.
  # You can create the tag locally, but not push it, and run GoReleaser.
  # It'll then set the `target_commitish` portion of the GitHub release to the
  # value you set here.
  # Only works on GitHub.
  # target_commitish: "{{ .Commit }}"

  # If set, will create a release discussion in the category specified.
  #
  # Warning: do not use categories in the 'Announcement' format.
  #  Check https://github.com/goreleaser/goreleaser/issues/2304 for more info.
  #
  # Default is empty.
  discussion_category_name: Releases

  # Set this to true if you want to disable just the artifact upload to the SCM.
  # If this is true, GoReleaser will still create the release with the
  # changelog, but won't upload anything to it.
  skip_upload: false

# Docker configuration for multi-arch container images (v2 format)
dockers_v2:
  - images:
      - "ghcr.io/daniel-le97/sandstorm-tracker"
    tags:
      - "v{{ .Version }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.description": "Insurgency: Sandstorm server stats tracker"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/daniel-le97/sandstorm-tracker"

# snapcrafts:
#   - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#     summary: CLI tool for downloading from https://banned.video
#     description: |
#       A comprehensive command-line tool for downloading and managing content
#       from banned.video with interactive TUI, database management, and torrent support.
#     grade: stable
#     confinement: strict
#     publish: true
#     license: MIT
#     base: core20
#     apps:
#       banned:
#         plugs: ["home", "network", "removable-media"]

# nfpms:
#   - file_name_template: '{{ .ConventionalFileName }}'
#     id: packages
#     homepage: https://github.com/daniel-le97/banned-cli
#     description: |-
#       A comprehensive CLI tool for downloading and managing content from banned.video
#       with interactive TUI, database management, and torrent support.
#     maintainer: Your Name <your.email@domain.com>
#     license: MIT
#     vendor: Your Organization
#     bindir: /usr/bin
#     section: utils
#     contents:
#       - src: ./README.md
#         dst: /usr/share/doc/banned/README.md
#       - src: ./LICENSE
#         dst: /usr/share/doc/banned/LICENSE
#     formats:
#     - apk
#     - deb
#     - rpm
#     - archlinux
#     deb:
#       lintian_overrides:
#         - statically-linked-binary
#         - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    # by specifying `packages` id here goreleaser will only use this publisher
    # with artifacts identified by this id
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.FURY_USER }}/
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
