version: "3"
tasks:
  goreleaser-dev:
    desc: Run goreleaser in snapshot (dev) mode
    cmds:
      - goreleaser release --snapshot --clean
  goreleaser-release:
    desc: Run goreleaser for a full release
    cmds:
      - goreleaser release --clean
  build:
    desc: Build all Go binaries
    cmds:
      - go build ./...\
  dev:
    desc: run app with defaults (db sandstorm-tracker.db, port 8080, server hc)
    cmds:
      - go run main.go -paths="C:\Users\danie\code\sandstorm-admin-wrapper\sandstorm-server\Insurgency\Saved\Logs"
  web:
    desc: Run the web server (default db, port 8080)
    cmds:
      - go run ./cmd/web -db=sandstorm-tracker.db -port=8080 -server=hc
  test:
    desc: Run all Go tests
    cmds:
      - go test ./...
  sqlc:
    desc: Generate Go code from SQL queries
    dir: internal/db
    cmds:
      - sqlc generate
  fmt:
    desc: Run gofmt on all Go files
    cmds:
      - gofmt -w .
  clean:
    desc: Remove built binaries
    cmds:
      - go clean
  tail:
    desc: Tail the log file
    cmds:
      - go run ./cmd/tail.go -file="C:\Users\danie\code\sandstorm-admin-wrapper\sandstorm-server\Insurgency\Saved\Logs\60844f66-b93b-4fe1-afc4-a0a91b493865.log" -f
  tailmulti:
    desc: Tail multiple log files
    cmds:
      - go run ./cmd/tail.go  -file="C:\Users\danie\code\go\sandstorm-trackerv2\hc.log" -f -writer="C:\Users\danie\code\go\sandstorm-trackerv2\hc.log"
    