version: "3"
tasks:
  tags:
    desc: create git tag for current version
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./scripts/create-release-tag.ps1
  goreleaser-dev:
    desc: Run goreleaser in snapshot (dev) mode (no Docker builds)
    cmds:
      - powershell -ExecutionPolicy Bypass -Command ". ./scripts/load-env.ps1; goreleaser release --snapshot --clean --skip=docker"
  goreleaser-release:
    desc: Run goreleaser for a full release with Docker image publishing
    cmds:
      - powershell -ExecutionPolicy Bypass -Command ". ./scripts/load-env.ps1; goreleaser release --clean --skip=docker"
  build:
    desc: Build all Go binaries
    cmds:
      - go build .
  dev:
    desc: run app with defaults
    cmds:
      - task reset
      - task superuser
      # - task stop
      - go run main.go serve
  test:
    desc: Run all Go tests
    cmds:
      - go test ./...
  test-integration:
    desc: Run all integration tests
    cmds:
      - go test ./tests/integration/... -count=1
  fmt:
    desc: Run gofmt on all Go files
    cmds:
      - gofmt -w .
  superuser:
    desc: Create an initial superuser account
    cmds:
      - go run . superuser create test@example.com password123
  clean:
    desc: Remove built binaries
    cmds:
      - go clean
  reset:
    desc: Remove pb_data directory to reset database
    cmds:
      - powershell -Command "if (Test-Path pb_data) { Remove-Item -Recurse -Force pb_data; Write-Host 'pb_data removed' } else { Write-Host 'pb_data does not exist' }"
  kill-tracker:
    desc: Kill all running sandstorm-tracker.exe processes
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./scripts/kill-tracker.ps1
  kill-server:
    desc: Kill all running Insurgency server processes (not the game client)
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./scripts/kill-server.ps1
  start:
    desc: Start Insurgency server with default config
    cmds:
      - task stop
      - go run ".\tools\servermgr\main.go" start --all
  stop:
    desc: Stop Insurgency servers
    cmds:
      - go run ".\tools\servermgr\main.go" stop --all
  status:
    desc: check status of Insurgency servers
    cmds:
      - go run ".\tools\servermgr\main.go" status
  update-server:
    desc: Update Insurgency server to latest version
    cmds:
      - task stop
      - go run ".\tools\servermgr\main.go" update-steamcmd
      - go run ".\tools\servermgr\main.go" update-game
  update-pb-client:
    desc: Update self-hosted PocketBase JS client (ES module)
    cmds:
      - powershell -Command "Invoke-WebRequest -Uri 'https://cdn.jsdelivr.net/npm/pocketbase/dist/pocketbase.es.mjs' -OutFile 'assets/static/pocketbase.es.mjs'"
      - echo "PocketBase client updated successfully"

  # Docker Development Tasks
  docker-up:
    desc: Start Docker container
    cmds:
      - docker-compose up -d

  docker-down:
    desc: Stop Docker container
    cmds:
      - docker-compose down

  docker-logs:
    desc: View Docker container logs
    cmds:
      - docker-compose logs -f sandstorm-tracker

  docker-fresh:
    desc: Clean rebuild with fresh data
    prompt: "This will delete all data. Continue?"
    cmds:
      - docker-compose down -v
      - docker-compose up --build

  docker-reset:
    desc: Reset database only
    cmds:
      - docker-compose down -v
      - docker-compose up -d
