version: "3"
tasks:
  goreleaser-dev:
    desc: Run goreleaser in snapshot (dev) mode
    cmds:
      - goreleaser release --snapshot --clean
  goreleaser-release:
    desc: Run goreleaser for a full release
    cmds:
      - goreleaser release --clean
  build:
    desc: Build all Go binaries
    cmds:
      - go build .
  dev:
    desc: run app with defaults
    cmds:
      - task reset
      - task superuser
      - task stop
      - go run main.go serve
  test:
    desc: Run all Go tests
    cmds:
      - go test ./...
  fmt:
    desc: Run gofmt on all Go files
    cmds:
      - gofmt -w .
  superuser:
    desc: Create an initial superuser account
    cmds:
      - go run . superuser create test@example.com password123
  clean:
    desc: Remove built binaries
    cmds:
      - go clean
  reset:
    desc: Remove pb_data directory to reset database
    cmds:
      - powershell -Command "if (Test-Path pb_data) { Remove-Item -Recurse -Force pb_data; Write-Host 'pb_data removed' } else { Write-Host 'pb_data does not exist' }"
  kill-server:
    desc: Kill all running Insurgency server processes (not the game client)
    cmds:
      - powershell -ExecutionPolicy Bypass -File ./scripts/kill-server.ps1
  start:
    desc: Start Insurgency server with default config
    cmds:
      - task build
      - task stop
      - ./sandstorm-tracker.exe server start --all
  stop:
    desc: Stop Insurgency servers
    cmds:
      - ./sandstorm-tracker.exe server stop --all

