// This file is now deprecated - use `bun test` instead
console.log( '🚀 Bun Test Suite Migration Complete!\n' );
console.log( 'The test suite has been migrated to use Bun\'s built-in test runner.' );
console.log( 'Please run tests using:' );
console.log( '' );
console.log( '  bun test                    # Run all tests' );
console.log( '  bun test --watch           # Run tests in watch mode' );
console.log( '  bun test event-parsing     # Run specific test file' );
console.log( '  bun test --concurrent      # Run tests concurrently' );
console.log( '' );
console.log( 'Available test files:' );
console.log( '  • tests/event-parsing.test.ts     - Event parsing and validation' );
console.log( '  • tests/weapon-mapping.test.ts    - Weapon name mapping' );
console.log( '  • tests/database.test.ts          - Database operations' );
console.log( '  • tests/chat-commands.test.ts     - Chat command responses' );
console.log( '  • tests/integration.test.ts       - End-to-end integration' );
console.log( '  • tests/playtime.test.ts          - Playtime tracking' );
console.log( '  • tests/file-watcher.test.ts      - File monitoring' );
console.log( '' );
console.log( '🎉 Use `bun test` to run the modern test suite!' );