[[servers]]
id = "server-1"
name = "Main Server"
logPath = "/tmp"
serverId = "60844f66-b93b-4fe1-afc4-a0a91b493865"
enabled = true
description = "Primary Sandstorm server"

[database]
path = "test_stats.db"
enableWAL = true
cacheSize = 1000

[logging]
level = "info"
enableServerLogs = true

[performance]
debounceDelay = 150
maxConcurrentWatchers = 5
